Update Kernel_build2.yml

diff --git a/.github/workflows/Kernel_build2.yml b/.github/workflows/Kernel_build2.yml
--- a/.github/workflows/Kernel_build2.yml
+++ b/.github/workflows/Kernel_build2.yml
@@ -45,134 +45,201 @@ jobs:
     permissions:
       contents: write
     steps:
-    - name: Display Inputs
+    
+    - name: Display User Inputs
       run: |
-        echo "Build Title: ${{ github.event.inputs.BUILD_TITLE }}"
+        echo "::group::User Environment Variables"
+        echo "Custom Build Title: ${{ github.event.inputs.BUILD_TITLE }}"
         echo "Codename: ${{ github.event.inputs.CODENAME }}"
-        echo "Source: ${{ github.event.inputs.KERNEL_SOURCE }} (${{ github.event.inputs.KERNEL_SOURCE_BRANCH }})"
-        echo "Defconfig: ${{ github.event.inputs.DEFCONFIG }}"
-        echo "AnyKernel: ${{ github.event.inputs.ANYKERNEL_URL }} (${{ github.event.inputs.ANYKERNEL_BRANCH }})"
-        echo "Notification: ${{ github.event.inputs.SEND_NOTIFICATION }}"
-        echo "KernelSU: ${{ github.event.inputs.ENABLE_KERNELSU }}"
+        echo "Kernel Source: ${{ github.event.inputs.KERNEL_SOURCE }}/tree/${{ github.event.inputs.KERNEL_SOURCE_BRANCH }}"
+        echo "Kernel Defconfig: ${{ github.event.inputs.DEFCONFIG }}"
+        echo "AnyKernel Url: ${{ github.event.inputs.ANYKERNEL_URL }}/tree/${{ github.event.inputs.ANYKERNEL_BRANCH }}"
+        echo "Send Notification: ${{ fromJSON('["No", "Yes"]')[fromJSON(github.event.inputs.SEND_NOTIFICATION)] }}"
+        echo "KernelSU: ${{ fromJSON('["No", "Yes"]')[fromJSON(github.event.inputs.ENABLE_KERNELSU)] }}"
+        echo "::endgroup::"
 
-    - name: Init Workspace
+    - name: Initialize workspace
       run: |
-        mkdir workspace && cd workspace
+        mkdir workspace
+        cd workspace
+
         echo "current_date=$(date +'%d %B %Y')" >> $GITHUB_OUTPUT
-        echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT
         echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
-        echo "kernelsu=${{ github.event.inputs.ENABLE_KERNELSU }}" >> $GITHUB_OUTPUT
+        echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT
+        echo "kernelsu=${{ fromJSON('["No", "Yes"]')[fromJSON(github.event.inputs.ENABLE_KERNELSU)] }}" >> $GITHUB_OUTPUT
         echo "build_title=${{ github.event.inputs.BUILD_TITLE || github.event.inputs.CODENAME }}" >> $GITHUB_OUTPUT
       id: workspace
-
-    - name: Notify Start
-      if: ${{ fromJSON(github.event.inputs.SEND_NOTIFICATION) && secrets.TELEGRAM_TO != '' }}
+      
+    - name: Send Telegram notification for start build
       uses: appleboy/telegram-action@master
+      env: 
+        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
       with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
+        disable_web_page_preview: true
         message: |
           <b>${{ github.event.inputs.BUILD_TITLE }}</b>
-          <b>⚒️ Kernel Build Started</b>
-
+          <b>⚒️Kernel Build Start⚒️</b>
+          
           <b>📱 Device</b>: Xiaomi Redmi 9C
           <b>💾 Codename</b>: ${{ github.event.inputs.CODENAME }}
           <b>🏷️ Branch</b>: ${{ github.event.inputs.KERNEL_SOURCE_BRANCH }}
           <b>🗓️ Date</b>: ${{ steps.workspace.outputs.current_date }}
-
+          
+          Build by @dhamarar
+          
           <b>Action</b>: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
         format: html
-
-    - name: Install Dependencies & Clang
+        
+    - name: Prepare the build environment
       run: |
-        sudo apt update && sudo apt install -y bc curl git zip flex libssl-dev \
-          python2 python3 gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libfl-dev
-        mkdir clang && cd clang
-        wget https://github.com/ZyCromerZ/Clang/releases/download/11.1.0-20220724-release/Clang-11.1.0-20220724.tar.gz
-        tar -xf *.tar.gz
+        sudo apt update -y && sudo apt upgrade -y && sudo apt-get install -y bc flex curl git zip ftp libncurses5 libssl-dev lftp zstd wget libfl-dev python2 python3 libarchive-tools gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
+        curl -LSs "https://raw.githubusercontent.com/rsuntk/toolchains/refs/heads/README/clone.sh" | bash -s clang-11
         echo "tools-folder=$(pwd)" >> $GITHUB_OUTPUT
       working-directory: ${{ steps.workspace.outputs.workspace-folder }}
       id: tools
 
-    - name: Clone Kernel Source
+    - name: Clone kernel source
       run: |
         git clone --depth=1 ${{ github.event.inputs.KERNEL_SOURCE }} -b ${{ github.event.inputs.KERNEL_SOURCE_BRANCH }} kernel_tree
         echo "kernel-folder=$(pwd)/kernel_tree" >> $GITHUB_OUTPUT
       working-directory: ${{ steps.workspace.outputs.workspace-folder }}
       id: kernel
 
-    - name: Add KernelSU
-      if: ${{ github.event.inputs.ENABLE_KERNELSU }}
+    - name: Adding KernelSU
+      if: ${{ steps.workspace.outputs.kernelsu == 'Yes' }}
       run: |
+        if [ -d "KernelSU" ]; then
+          rm -rf "KernelSU"
+        fi
+        if [ -d "drivers/kernelsu" ]; then
+          rm -rf "drivers/kernelsu"
+        fi
         curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-dev
       working-directory: ${{ steps.kernel.outputs.kernel-folder }}
 
-    - name: Build Kernel
+    - name: Building kernel
       run: |
-        export CLANGDIR="${{ steps.tools.outputs.tools-folder }}"
-        cd ${{ steps.kernel.outputs.kernel-folder }}
+        export CLANGDIR="${{ steps.tools.outputs.tools-folder }}/clang-11"
+        rm -f ${{ steps.kernel.outputs.kernel-folder }}/out/compile.log
+        mkdir -p ${{ steps.kernel.outputs.kernel-folder }}/out
+
+        export KBUILD_BUILD_USER="DhamarAr"
+        export KBUILD_BUILD_HOST="Ordinary_Being"
+        export USE_CCACHE=1
+        export PATH="$CLANGDIR/bin:$PATH"
+        
+        make clean && make mrproper
         make O=out ARCH=arm64 ${{ github.event.inputs.DEFCONFIG }}_defconfig
-        make -j$(nproc --all) O=out ARCH=arm64 LLVM=1 LLVM_IAS=1 \
-          CC=clang LD=ld.lld CROSS_COMPILE=aarch64-linux-gnu- \
-          CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
-          HOSTCC=clang HOSTCXX=clang++ || exit 1
-        echo "elapsed_time=$(($(date +%s) - ${{ steps.workspace.outputs.start_time }}))" >> $GITHUB_OUTPUT
+
+        fulmen () {
+         make -j$(nproc --all) O=out LLVM=1 LLVM_IAS=1 \
+         ARCH=arm64 \
+         CC=clang \
+         LD=ld.lld \
+         AR=llvm-ar \
+         AS=llvm-as \
+         NM=llvm-nm \
+         STRIP=llvm-strip \
+         OBJCOPY=llvm-objcopy \
+         OBJDUMP=llvm-objdump \
+         READELF=llvm-readelf \
+         HOSTCC=clang \
+         HOSTCXX=clang++ \
+         HOSTAR=llvm-ar \
+         HOSTLD=ld.lld \
+         CROSS_COMPILE=aarch64-linux-gnu- \
+         CROSS_COMPILE_ARM32=arm-linux-gnueabi-
+        }
+
+        fulmen 2>&1 | tee -a ${{ steps.kernel.outputs.kernel-folder }}/out/compile.log
+    
+        echo "elapsed_time=$(echo "$(date +%s)"-"${{ steps.workspace.outputs.start_time }}" | bc)" >> $GITHUB_OUTPUT
+      working-directory: ${{ steps.kernel.outputs.kernel-folder }}
       id: build
 
-    - name: Pack with AnyKernel
+    - name: AnyKernel3
+      if: ${{ success() && github.event.inputs.ANYKERNEL_URL != '' }}
+      continue-on-error: true
       run: |
-        git clone --depth=1 ${{ github.event.inputs.ANYKERNEL_URL }} -b ${{ github.event.inputs.ANYKERNEL_BRANCH }} AnyKernel3
-        cp ${{ steps.kernel.outputs.kernel-folder }}/out/arch/arm64/boot/Image.gz AnyKernel3/
+        if [[ -z "${{ github.event.inputs.ANYKERNEL_BRANCH }}" ]]; then
+          anykernel_branch=${{ github.event.inputs.DEFCONFIG }}
+        else
+          anykernel_branch=${{ github.event.inputs.ANYKERNEL_BRANCH }}
+        fi
+        git clone --recursive --depth=1 ${{ github.event.inputs.ANYKERNEL_URL }} -b $anykernel_branch AnyKernel3
+        
+        if [ ! -f "Image.gz" ]; then
+          echo "Error: Tidak menemukan Image.gz atau Image!"
+          exit 1
+        fi
+        
+        if [ -e "Image.gz" ]; then
+          cp -f Image.gz AnyKernel3
+          echo "Warning: Don't forget about dtb."
+        fi
+        
+        name=AnyKernel3-FulmenKernel-${{ github.event.inputs.CODENAME }}${{ fromJSON('["", "-KSU"]')[fromJSON(github.event.inputs.ENABLE_KERNELSU)] }}-$(date +%Y%m%d).zip
         cd AnyKernel3
-        name=FulmenKernel-${{ github.event.inputs.CODENAME }}$( [ "${{ github.event.inputs.ENABLE_KERNELSU }}" == "true" ] && echo "-KSU" ).zip
-        zip -r9 $name *
+        zip -q -r $name *
         mv $name ../
         echo "zipname=$name" >> $GITHUB_OUTPUT
-      working-directory: ${{ steps.workspace.outputs.workspace-folder }}
+      working-directory: ${{ steps.kernel.outputs.kernel-folder }}/out/arch/arm64/boot/
       id: anykernel
 
+    - name: Check the output directory before uploading
+      run: |
+        ls -al ${{ steps.kernel.outputs.kernel-folder }}/out/arch/arm64/boot/
     - uses: actions/upload-artifact@v4
-      if: ${{ success() }}
+      if: ${{ success() && github.event.inputs.UPLOAD_TO_RELEASE != 'true' }}
       with:
-        name: KernelZip
-        path: ${{ steps.workspace.outputs.workspace-folder }}/${{ steps.anykernel.outputs.zipname }}
+        name: Image.gz
+        path: ${{ steps.kernel.outputs.kernel-folder }}/out/arch/arm64/boot/Image.gz
 
-    - name: Notify Success
-      if: ${{ fromJSON(github.event.inputs.SEND_NOTIFICATION) && steps.build.outcome == 'success' && secrets.TELEGRAM_TO != '' }}
+    - name: Send Telegram notification for success
       uses: appleboy/telegram-action@master
+      env: 
+        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
+      if: ${{ success() && steps.anykernel.outputs.zipname != '' && env.TELEGRAM_TO != '' && github.event.inputs.SEND_NOTIFICATION == 'true' }}
       with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
-        document: ${{ steps.workspace.outputs.workspace-folder }}/${{ steps.anykernel.outputs.zipname }}
+        disable_web_page_preview: true
+        document: ${{ steps.kernel.outputs.kernel-folder }}/out/arch/arm64/boot/${{ steps.anykernel.outputs.zipname }}
         message: |
           <b>${{ steps.workspace.outputs.build_title }}</b>
-          <b>✅ Kernel Build Success</b>
-
-          <b>📱 Device</b>: Xiaomi Redmi 9C
+          <b>✅ Kernel Successfully Build</b>
+          
+          <b>📱 Device</b>: Xiaomi Redmi 9C 
           <b>💾 Codename</b>: ${{ github.event.inputs.CODENAME }}
           <b>🏷️ Branch</b>: ${{ github.event.inputs.KERNEL_SOURCE_BRANCH }}
-          <b>⏳ Time</b>: ${{ steps.build.outputs.elapsed_time }} sec
-          <b>📦 Zip</b>: ${{ steps.anykernel.outputs.zipname }}
-          <b>☯️ KernelSU</b>: ${{ github.event.inputs.ENABLE_KERNELSU }}
-
+          <b>📦 Zip Name</b>: ${{ steps.anykernel.outputs.zipname }}
+          <b>⏳ Build Time</b>: ${{ steps.build.outputs.elapsed_time }} seconds.
+          <b>🗓️ Date</b>: ${{ steps.workspace.outputs.current_date }}
+          <b>☯️ KernelSU</b>: ${{ steps.workspace.outputs.kernelsu }}
+          
+          Build by @dhamarar
+          
+          <b>Kernel Source</b>: ${{ github.event.inputs.KERNEL_SOURCE }}
           <b>Action</b>: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
         format: html
 
-    - name: Notify Failure
-      if: ${{ fromJSON(github.event.inputs.SEND_NOTIFICATION) && failure() && secrets.TELEGRAM_TO != '' }}
+    - name: Send Telegram notification for failure
       uses: appleboy/telegram-action@master
+      env: 
+        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
+      if: ${{ failure() && env.TELEGRAM_TO != '' && github.event.inputs.SEND_NOTIFICATION == 'true' }}
       with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
+        disable_web_page_preview: true
+        document: ${{ steps.kernel.outputs.kernel-folder }}/out/compile.log
         message: |
           <b>${{ steps.workspace.outputs.build_title }}</b>
-          <b>❌ Kernel Build Failed</b>
-
-          <b>📱 Device</b>: Xiaomi Redmi 9C
-          <b>💾 Codename</b>: ${{ github.event.inputs.CODENAME }}
-          <b>🏷️ Branch</b>: ${{ github.event.inputs.KERNEL_SOURCE_BRANCH }}
-          <b>☯️ KernelSU</b>: ${{ github.event.inputs.ENABLE_KERNELSU }}
-
-          Check logs at:
-          <b>${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}</b>
+          <b>❌Failed building kernel</b>, check ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} for more info.
+          
+          <b>Kernel Source</b>: ${{ github.event.inputs.KERNEL_SOURCE }}
+          <b>KernelSU</b>: ${{ steps.workspace.outputs.kernelsu }}
         format: html
+      continue-on-error: true
